### PR TITLE
SQL: segfault after make_select() in VTMD

### PR DESCRIPTION
**Pull request by kevgs**

### CODE REVIEW

**Review by midenok — CHANGES_REQUESTED** [review]
1. There is other `make_select()` in vtmd.cc.
2. Why you do `init_read_record()`, `info.read_record()` in this case?

**Comment by kevgs** [comment]
> There is other make_select() in vtmd.cc.

`NULL` dereference is impossible after other `make_select()`.

> Why you do init_read_record(), info.read_record() in this case?

To take value or a first read row. Is it logically incorrect? I don't know. Initially I planned to use `VTMD_table::find_archive_name` only for `AS OF` cases. Now it is used for everything and something works incorrect, e.g.
```sql
set versioning_alter_history = survive;

create or replace table t (a int) with system versioning;
insert into t values (1);
set @ts1 = now(6);
alter table t add column b int;
update t set a=2;
set @ts2 = now(6);
alter table t drop column b;
update t set a = 3;

select * from t for system_time all;
a	sys_trx_start	sys_trx_end
1	2017-10-04 12:28:07.760174	2017-10-04 12:28:07.761250
```

**Comment by midenok** [comment]
> NULL dereference is impossible after other make_select().

What is semantics of NULL return value?

**Comment by midenok** [comment]
Did you test `get_archive_tables()` under empty VTMD condition?

**Review by midenok — APPROVED** [review]

**Comment by kevgs** [comment]
> What is semantics of NULL return value?

It is fine when `*error == 0` and means `CONDS` was `NULL`. And it's allocation failure when `CONDS != NULL`

**Comment by kevgs** [comment]
> Did you test get_archive_tables() under empty VTMD condition?

Looks like query `select * from t` works fine.

Here is a separate issue for related questions https://github.com/tempesta-tech/mariadb/issues/277

**Pull request merged**
