### PR TITLE
SQL: forced versioning mode for CREATE TABLE, SELECT, SHOW CREATE

### LINKED ISSUE #32: Add "forced versioning" option

### PR DESCRIPTION
**Pull request by midenok**
`DESCRIBE` is not hidden since it's too difficult to hide records from INFORMATION_SCHEMA.

Please, review after #40 .

Closes #32

### CODE REVIEW

**Review by avodaniel — COMMENTED** [review]
Looks OK, except:
- I don't like that the variables are set only through plugin load/unload and that user cannot see them.
- Test isn't present.
- Is DESCRIBE statement covered?

**Comment by midenok** [comment]
As we dicussed before, the purpose of this mod is for development needs only (at least for first time). So there is no need in conf variables (I thought I told it, but maybe I forgot to mention, sorry). By the same reason, there is no need in tests.

Daniel, you may merge your branch with variables and tests later when it will be needed.

**Comment by avodaniel** [comment]
OK, then I think this patch s OK and can be merged.

**Comment by midenok** [comment]
Postponed until 0.4.

**Pull request closed without merging**
