### PR TITLE
SQL: compare TRX_ID fields against timestamps [closes 231]

### PR DESCRIPTION
**Pull request by midenok**
Please, review.
versioning.rpl_row for innodb fails (depends on #234).

### CODE REVIEW

**Comment by kevgs** [comment]
Disabling use of IB `trx_id` doesn't seems correct.

Eventually we need IB tables to work with both `timestamp(6)` and `bigint unsigned`.

Current behaviour is a bit strange:
```sql
select * from t for system_time all;
a	sys_trx_start	sys_trx_end
1	1284	18446744073709551615
select * from t where sys_trx_start <= 1284;
a	sys_trx_start	sys_trx_end
1	1284	18446744073709551615
select * from t where sys_trx_start <= 1284 + 1;
query 'select * from t where sys_trx_start <= 1284 + 1' failed: 4102: TRX_ID 1285 not found in VTQ
```

```sql
query 'select * from t where sys_trx_start <= sys_trx_start + 1' failed: 4102: TRX_ID 0 not found in VTQ
```

```sql
select * from t for system_time all;
a	sys_trx_start	sys_trx_end
1	1284	18446744073709551615
select * from t where sys_trx_start = (sys_trx_start + 1 - 1);
query 'select * from t where sys_trx_start = (sys_trx_start + 1 - 1)' failed: 4102: TRX_ID 0 not found in VTQ
```

Use will be able to get `trx_id` values from audit plugin or use any arbitrary value.

**Comment by midenok** [comment]
Yes, it is a bit strange:
when you compare `sys_trx_start <= 1284` it will convert both operands to timestamps (by looking to VTQ) and then compare timestamps. When you do `sys_trx_start + 0 <= 1284` it will compare numerical values. So, this is how its done.

By doing it without `VTQ_COMMIT_TS()` we are not depending on any functions when using VIEWs. Maybe better solution would be to return back to `VTQ_COMMIT_TS()`, rename it to `COMMIT_TIMESTAMP()` and do something like `sys_trx_start <= COMMIT_TIMESTAMP(1284)`?

**Comment by kevgs** [comment]
What about comparing trx_ids in `sys_trx_start < 1234` and comparing timestamps in `sys_trx_start < '2017-01-01 01:01:01'`?

**Comment by midenok** [comment]
Not bad idea at all... But it requires `COMMIT_TIMESTAMP()` anyway because we compare timestamps in `AS OF` query.

**Comment by kevgs** [comment]
In queries like `for system_time as of timestamp '2017-01-01 01:01:01'` we should translate `trx_ids` to timestamps, indeed.
And in queries like `for system_time as of transaction 100500` we should compare `trx_ids`.

**Comment by midenok** [comment]
No, we shouldn't. We must not!

**Comment by kevgs** [comment]
Let me describe how I understand [this comment](https://github.com/MariaDB/server/commit/0fd3b8fc9ff6cc2b73d2e76d2442e68ee77a0eb3#commitcomment-22723148) and what we need to do in general.

```sql
create table t (
  a int,
  sys_trx_start timestamp(6) generated always as row start,
  sys_trx_end timestamp(6) generated always as row end,
  period for system_time(sys_trx_start, sys_trx_end)
) with system versioning engine myisam;

insert into t values (1);

select a, sys_trx_start, sys_trx_end from t for system_time as of timestamp now(6);

a	sys_trx_start	sys_trx_end
1	2017-07-21 18:12:54.920822	2038-01-19 06:14:07.000000
```

We use timestamp here in `AS OF` clause. `sys_trx` fields store timestamps too.

```sql
create table t (
  a int,
  sys_trx_start timestamp(6) generated always as row start,
  sys_trx_end timestamp(6) generated always as row end,
  period for system_time(sys_trx_start, sys_trx_end)
) with system versioning engine innodb;

insert into t values (1);

select a, sys_trx_start, sys_trx_end from t for system_time as of timestamp now(6);

a	sys_trx_start	sys_trx_end
1	2017-07-21 18:12:54.920822	2038-01-19 06:14:07.000000

select a, sys_trx_start, sys_trx_end from t for system_time as of transaction 100500;

a	sys_trx_start	sys_trx_end
1	2017-07-21 18:12:54.920822	2038-01-19 06:14:07.000000
```

We create `InnoDB` table exactly the same way. And for user it looks like it stores timestaps, but actually stores trx_ids. All conversions happens under the hood.

But additionally we're able to use arbitrary trx_ids in `AS OF` queries when we need transaction level precision. And it compares trx_ids, not timestamps.

**Comment by midenok** [comment]
This task is not the subject of #209. Don't mix them. There is no sense in raw comparing TRX_ID (apart from VTQ_TRX_SEES()).

**Comment by kevgs** [comment]
If I understand correct, you basically disable this codepath in this patch. That's why I have questions. Do you plan to enable it later?
```c++
     {
        DBUG_ASSERT(table->table->s && table->table->s->db_plugin);
        handlerton *hton= plugin_hton(table->table->s->db_plugin);
        DBUG_ASSERT(hton);

        Item *trx_id0, *trx_id1;

        switch (vers_conditions.type)
        {
        case FOR_SYSTEM_TIME_UNSPECIFIED:
          curr= newx Item_int(thd, ULONGLONG_MAX);
          cond1= newx Item_func_eq(thd, row_end2, curr);
          break;
        case FOR_SYSTEM_TIME_AS_OF:
          trx_id0= vers_conditions.unit == UNIT_TIMESTAMP ?
            newx Item_func_vtq_id(thd, hton, vers_conditions.start, VTQ_TRX_ID) :
            vers_conditions.start;
          cond1= newx Item_func_vtq_trx_sees_eq(thd, hton, trx_id0, row_start);
          cond2= newx Item_func_vtq_trx_sees(thd, hton, row_end, trx_id0);
          break;
        case FOR_SYSTEM_TIME_FROM_TO:
        case FOR_SYSTEM_TIME_BETWEEN:
          if (vers_conditions.unit == UNIT_TIMESTAMP)
          {
            trx_id0= newx Item_func_vtq_id(thd, hton, vers_conditions.start, VTQ_TRX_ID, true);
            trx_id1= newx Item_func_vtq_id(thd, hton, vers_conditions.end, VTQ_TRX_ID, false);
          }
          else
          {
            trx_id0= vers_conditions.start;
            trx_id1= vers_conditions.end;
          }

          cond1= vers_conditions.type == FOR_SYSTEM_TIME_FROM_TO ?
            newx Item_func_vtq_trx_sees(thd, hton, trx_id1, row_start) :
            newx Item_func_vtq_trx_sees_eq(thd, hton, trx_id1, row_start);
          cond2= newx Item_func_vtq_trx_sees_eq(thd, hton, row_end, trx_id0);
          break;
        case FOR_SYSTEM_TIME_BEFORE:
          trx_id0= vers_conditions.unit == UNIT_TIMESTAMP ?
            newx Item_func_vtq_id(thd, hton, vers_conditions.start, VTQ_TRX_ID) :
            vers_conditions.start;
          cond1= newx Item_func_lt(thd, row_end, trx_id0);
          break;
        default:
          DBUG_ASSERT(0);
        }
      }
```

**Comment by midenok** [comment]
Do you mean `trx_sees()` functionality? Of course I plan to recover it when we solve issue with algorithm.

**Review by kevgs — APPROVED** [review]

**Pull request merged**
