### PR TITLE
MDEV-14820 System versioning is applied incorrectly to CTEs

### PR DESCRIPTION
**Pull request by midenok**
Closes tempesta-tech#476

### CODE REVIEW

**Comment by kevgs** [comment]
```sql
create or replace table numbers (n int not null) with system versioning;
insert into numbers values (-1), (1), (2), (3), (4);
set @ts = current_timestamp;

with positive_numbers as
(
select n from numbers for system_time as of @ts where 0 < n
)
select * from positive_numbers;
n

with positive_numbers as
(
select n from numbers for system_time as of current_timestamp where 0 < n
)
select * from positive_numbers;
n
1
2
3
4
```

I expect the same results for both selects. This looks like a bug.

**Comment by midenok** [comment]
Doesn't look like bug unless `current_timestamp(6)` is used.

**Comment by kevgs** [comment]
Oh. I've forgot that `(6)` is implicit only when inside `FOR SYSTEM_TIME`

**Comment by kevgs** [comment]
I suggest to make this:

```diff
diff --git a/mysql-test/suite/versioning/r/cte.result b/mysql-test/suite/versioning/r/cte.result
diff --git a/mysql-test/suite/versioning/r/cte.result b/mysql-test/suite/versioning/r/cte.result
index bec704c6efc..810e4036a15 100644
--- a/mysql-test/suite/versioning/r/cte.result
+++ b/mysql-test/suite/versioning/r/cte.result
@@ -1,4 +1,3 @@
-set default_storage_engine=innodb;
 create or replace table dept (
 dept_id int(10) primary key, 
 name varchar(100)
@@ -42,7 +41,7 @@ from emp for system_time as of timestamp @ts_1 as e,
 ancestors as a
 where e.mgr = a.emp_id
 )
-select * from ancestors;
+select * from ancestors order by emp_id;
 emp_id name    mgr     salary
 1      bill    NULL    1000
 20     john    1       500
@@ -61,7 +60,7 @@ ancestors as a
 where e.mgr = a.emp_id
 )
 select * from ancestors
-for system_time as of timestamp @ts_1;
+for system_time as of timestamp @ts_1 order by emp_id;
 emp_id name    mgr     salary
 1      bill    NULL    1000
 20     john    1       500
diff --git a/mysql-test/suite/versioning/t/cte.test b/mysql-test/suite/versioning/t/cte.test
index a6fc762fac7..5afbd78d5a3 100644
--- a/mysql-test/suite/versioning/t/cte.test
+++ b/mysql-test/suite/versioning/t/cte.test
@@ -1,5 +1,5 @@
--- source include/have_innodb.inc
-set default_storage_engine=innodb;
+-- source suite/versioning/engines.inc
+
 create or replace table dept (
   dept_id int(10) primary key, 
   name varchar(100)
@@ -49,7 +49,7 @@ as
        ancestors as a
   where e.mgr = a.emp_id
 )
-select * from ancestors;
+select * from ancestors order by emp_id;
 
 with recursive
 ancestors
@@ -65,7 +65,7 @@ as
   where e.mgr = a.emp_id
 )
 select * from ancestors
-for system_time as of timestamp @ts_1;
+for system_time as of timestamp @ts_1 order by emp_id;
 
 /* Expected 3 rows */
```

**Comment by kevgs** [comment]
The last query fails. This looks inconsistent. In one context `positive_numbers` is versioned, in another context it is not:

```sql
create or replace table numbers (n int not null)
with system versioning engine=myisam;
insert into numbers values (-1), (1), (2), (3), (4);
set @ts = current_timestamp(6);
with positive_numbers as (select n from numbers for system_time as of @ts where 0 < n),
even_numbers as (select n from positive_numbers where n % 2 = 0)
select * from positive_numbers;
n
1
2
3
4
with positive_numbers as (select n from numbers where 0 < n),
even_numbers as (select n from positive_numbers where n % 2 = 0)
select * from positive_numbers for system_time as of @ts;
n
1
2
3
4
with positive_numbers as (select n from numbers where 0 < n),
even_numbers as (select n from positive_numbers  for system_time as of @ts where n % 2 = 0)
select * from positive_numbers;
```

**Comment by midenok** [comment]
Last query fails with error:
```
ERROR 4124 (HY000): Table `positive_numbers` is not system-versioned
```
Only outer CTE instances are expected to accept `SYSTEM_TIME`. Let's discuss in chat if you wish.

**Comment by kevgs** [comment]
One more. Query work with a table with two distinct `FOR SYSTEM_TIME`.

```sql
create or replace table folks (
  id int,
  name varchar(100),
  father int,
  mother int) with system versioning;

insert into folks values
  (100, 'Alex', 20, 30),
  (20, 'Dad', 10, NULL),
  (30, 'Mom', NULL, NULL),
  (10, 'Grandpa Bill', NULL, NULL),
  (98, 'Sister Amy', 20, 30);

set @ts = current_timestamp(6);
update folks set name = 'Grandpa John' where name = 'Grandpa Bill';
update folks set name = 'Andrew' where name = 'Alex';

with recursive ancestors as (
  select * from folks	 
  where name = 'Andrew'
  union
  select f.*
  from folks as f, ancestors as a
  where
    f.id = a.father or f.id = a.mother
)
select * from ancestors;

with recursive ancestors as (
  select * from folks
  where name = 'Alex'
  union
  select f.*
  from folks for system_time as of current_timestamp as f, ancestors as a
  where
    f.id = a.father or f.id = a.mother
)
select * from ancestors for system_time as of @ts;
```

First query result:
```sql
id	name	father	mother
100	Andrew	20	30
20	Dad	10	NULL
30	Mom	NULL	NULL
10	Grandpa John	NULL	NULL
```

Second query result. Data is from different time points:
```sql
id	name	father	mother
100	Alex	20	30
20	Dad	10	NULL
30	Mom	NULL	NULL
10	Grandpa John	NULL	NULL
```

**Comment by kevgs** [comment]
Documentation on MariaDB CTE https://mariadb.com/kb/en/library/common-table-expressions/

**Review by kevgs — APPROVED** [review]

**Pull request merged**
