### PR TITLE
Style: related to DBUG_ASSERT usage

### PR DESCRIPTION
**Pull request by kevgs**
Thanks for the nice suggestion :)

### CODE REVIEW

**Comment by midenok** [comment]
In fact it is questionable which one looks better: whether to leave compiler optimize out `if` condition or variable assignment. Also, why do you call it _refactoring_? Refactoring involves big changes: dozens or hundreds of lines of code. This commit rather deserves 'Style: ' prefix or just 'Style fix' will be enough (no one will be interested in details on such commits). Also you may do such small and obvious changes directly, without pull request (build compilation and running insert, update, delete tests is necessary).

**Comment by avodaniel** [comment]
@midenok, are you really sure that compiler would optimize out:

```
if (x())
    ;
```

If it cannot be sure whether x() has any side effects or when it even knows that x() has some? Assertion macros usually explicitly removes conditions when debugging is disabled, like: https://github.com/natsys/mariadb_10.2/blob/natsys/trunk/include/my_dbug.h#L162 .

**Comment by kevgs** [comment]
Compiler will definitely optimize it by throwing out if.
And Style: is a better prefix, yes.

**Comment by kevgs** [comment]
Also compiler is able to optimize a dead store - it's simple.

**Comment by midenok** [comment]
Of course it will optimize. The point I tried to express was about producing less questions from humans. The code apart from correct execution should be obvious and easy to read.

**Comment by kevgs** [comment]
> The code apart from correct execution should be obvious and easy to read.

That's a very important topic, agreed. But different peoples have different opinion on that. IMO this version  is more readable. And I just can vote for what I think is better.

**Comment by midenok** [comment]
That's not so important to vote... What's done is good.

**Pull request merged**
